Se utilizó la API APOD (Astronomy Picture of the Day) de la NASA para recuperar publicaciones astronómicas y analizar aquellas relacionadas con la palabra asignada (Olvera Galeana Enrique)  "Northern Lights".

In [ ]:
import requests
import pandas as pd
import time

Una vez generada la Api key la ingresamos.

In [ ]:
api_key="wOgmtJdP7qWFLlOebSoGMHqed272IAiIfuOsrF8a"

 Creamos un dataframe para agregarle filas posteriormente.

In [ ]:
df_apod=pd.DataFrame()

df_apod

Empty DataFrame
Columns: []
Index: []

Generamos un rango de fechas para recorrer publicaciones en automatico.

In [ ]:
anios=range(
    1995,
    2026
)

list(anios)

[1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025]

Definimos la palabra asignada para buscar coincidencias dentro del campo "explanation" de cada publicación APOD

In [ ]:
palabra="northern lights"

palabra

'northern lights'

Se hizo un ciclo for para recorrer los años definidos previamente y realizar una solicitud a la API APOD de la NASA para cada año completo, esto con el fin de hacerlo por año y no por día fue reducir el número de solicitudes realizadas ya que la API puede semtirse amenazada.

In [ ]:
# Recorremos cada año para evitar miles de solicitudes diarias
for anio in anios:

    # Muestra el avance del proceso
    print(
        "Procesando:",
        anio
    )

    # Definimos fecha inicial y final del año
    inicio=f"{anio}-01-01"

    fin=f"{anio}-12-31"

    # Construimos la URL con API key y rango de fechas
    url=f"https://api.nasa.gov/planetary/apod?api_key={api_key}&start_date={inicio}&end_date={fin}"

    # Enviamos solicitud a la API
    response=requests.get(
        url
    )

    # Verificamos que la solicitud fue exitosa
    if response.status_code==200:

        # Convertimos la respuesta JSON a Python
        data=response.json()

        # Recorremos cada publicación APOD
        for registro in data:

            # Checamos que exista explicación
            if "explanation" in registro:

                # Convertimos texto a minúsculas
                texto=registro[
                    "explanation"
                ].lower()

                # Buscamos la palabra asignada
                if palabra in texto:

                    # Extraemos variables
                    apod_info={

                        "date":
                        registro.get(
                            "date"
                        ),

                        "title":
                        registro.get(
                            "title"
                        ),

                        "media_type":
                        registro.get(
                            "media_type"
                        ),

                        "copyright":
                        registro.get(
                            "copyright"
                        ),

                        "url":
                        registro.get(
                            "url"
                        )

                    }

                    # Convertimos el diccionario en una fila
                    mi_df=pd.DataFrame(
                        [apod_info]
                    )

                    # Agregamos resultados al DataFrame final
                    df_apod=pd.concat(
                        [df_apod,mi_df],
                        ignore_index=True
                    )

    # Pausa para evitar muchas solicitudes
    time.sleep(.3)

Procesando: 1995
Procesando: 1996
Procesando: 1997
Procesando: 1998
Procesando: 1999
Procesando: 2000
Procesando: 2001
Procesando: 2002
Procesando: 2003
Procesando: 2004
Procesando: 2005
Procesando: 2006
Procesando: 2007
Procesando: 2008
Procesando: 2009
Procesando: 2010
Procesando: 2011
Procesando: 2012
Procesando: 2013
Procesando: 2014
Procesando: 2015
Procesando: 2016
Procesando: 2017
Procesando: 2018
Procesando: 2019
Procesando: 2020
Procesando: 2021
Procesando: 2022
Procesando: 2023
Procesando: 2024
Procesando: 2025

Revisemos cuantos renglones y columnas tiene el dataframe

In [ ]:
df_apod.shape

(78, 5)

Inspeccionemos los primeros registros para ver la estrcutura.

In [ ]:
df_apod.head()

,date,title,media_type,copyright,url
0,2015-06-26,Planet Aurora,image,None,https://apod.nasa.gov/apod/image/1506/ISSauror...
1,2015-06-29,Sunspot Group AR 2339 Crosses the Sun,video,Stanislav Korotkiy\n(AstroAlert) &\nMikhail Ch...,https://www.youtube.com/embed/BejRxZAa66E?rel=0
2,2015-07-04,Aurora Australis,image,Robert Schwarz,https://apod.nasa.gov/apod/image/1507/Robert-S...
3,2015-08-03,A Proton Arc Over Lake Superior,image,Ken Williams,https://apod.nasa.gov/apod/image/1508/ProtonAr...
4,2015-09-04,Milky Way with Airglow Australis,image,Yuri Beletsky,https://apod.nasa.gov/apod/image/1509/airglow_...

Ahora veamos que estructura tiene el dataframe.

In [ ]:
df_apod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        78 non-null     object
 1   title       78 non-null     object
 2   media_type  78 non-null     object
 3   copyright   72 non-null     object
 4   url         78 non-null     object
dtypes: object(5)
memory usage: 3.2+ KB

Notemos que copyright presenta una menor cantidad de valores no nulos respecto a las demas columnas, esto indica la existencia de datos faltantes NaN.

Esto puede tomarse como una ambigüedad, ya que algunos recursos no especifican autor o institución propietaria.

Ahora, identifiquemos los datos faltantes

In [ ]:

df_apod.isna().sum()

date          0
title         0
media_type    0
copyright     6
url           0
dtype: int64

Con esto contamos cuántos valores faltan por columna.

Para las búsquedas de tu palabra, ¿cuántos resultados obtuviste?

In [ ]:
# Contamos recursos encontrados
len(df_apod)

78



Respuesta: Para la palabra Northern Lights se obtuvieron 78 resultados dentro de las publicaciones APOD descargadas desde la API de la NASA.

Para las búsquedas de tu palabra, ¿en qué rangos de fechas se introdujo el recurso?

In [ ]:
# Convertimos a formato fecha
df_apod["date"]=pd.to_datetime(
    df_apod["date"]
)

# Obtenemos primera y última fecha
df_apod["date"].min(),df_apod["date"].max()

(Timestamp('1997-01-01 00:00:00'), Timestamp('2025-12-12 00:00:00'))

Respuesta: Los recursos asociados a Northern Lights aparecen entre 1997-01-01 y 2025-12-12.

Para las búsquedas de tu palabra, ¿cuáles son los "media_type" más comunes?

In [ ]:
# Contamos tipos de recurso
df_apod[
    "media_type"
].value_counts()

media_type
image    77
video     1
Name: count, dtype: int64

Respuesta: El tipo de recurso mas comun fue image con 77 seguido de video con 1.

Para las búsquedas de tu palabra, ¿quiénes son los autores o instituciones propietaria de los derechos (i.e. el copyright)?

Primero limpiamos valores ambiguos

In [ ]:
# Convertimos valores faltantes
df_apod=df_apod.replace(
    "None",
    pd.NA
)

In [ ]:
# Autores más frecuentes
df_apod[
    "copyright"
].value_counts().head(10)

copyright
Göran Strand                                    4
Dennis Lehtonen                                 3
Yuichi Takasaka                                 3
Trygve Lindersen                                2
Clear Skies                                     2
Bjørnar\nG. Hansen,                             2
Stan Richards \n(NightSkyEvents.com)            2
Dave Ewoldt\n(Okarche, Oklahoma)                2
Stan Richard                                    2
Jimmy Westlake\n(Colorado\nMountain College)    2
Name: count, dtype: int64

Respuesta: Los recursos arrojan distintos autores y propietarios de derechos, los más frecuentes son Göran Strand yDennis Lehtonen.